version: '3.8'

services:
  backend:
    command: ["npm", "run", "dev"]
    environment:
      - NODE_ENV=development
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: always

  frontend:
    build:
      context: ./frontend/Green-Nest
      dockerfile: Dockerfile
    dns:
      - 8.8.8.8  
      - 8.8.4.4
    ports:
      - "8081:8081"
    volumes:
      - ./frontend/Green-Nest:/app
      - /app/node_modules
    restart: always

  mongo:
    image: mongo
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:

