# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: backend
#   template:
#     metadata:
#       labels:
#         app: backend
#     spec:
#       containers:
#         - name: backend
#           image: nabiazeenatzia/backend:latest
#           ports:
#             - containerPort: 5000
#           envFrom:
#             - configMapRef:
#                 name: backend-config
#             - secretRef:
#                 name: backend-secret
#           livenessProbe:
#             httpGet:
#               path: /health
#               port: 5000
#             initialDelaySeconds: 10
#             periodSeconds: 10
#           readinessProbe:
#             httpGet:
#               path: /ready
#               port: 5000
#             initialDelaySeconds: 5
#             periodSeconds: 5
#           resources:
#             requests:
#               cpu: "150m"
#               memory: "156Mi"
#             limits:
#               cpu: "250m"
#               memory: "256Mi"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nabiazeenatzia/backend:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5

