name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build Backend Container
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd backend
          npm install
      - name: Build Docker image for Backend
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:$GITHUB_SHA .

  # Build Frontend Container
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd frontend/Green-Nest
          npm install
      - name: Build Docker image for Frontend
        run: |
          cd frontend/Green-Nest
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:$GITHUB_SHA .

  # Run Unit Tests for Backend
  test_backend:
    runs-on: ubuntu-latest
    needs: build_backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd backend
          npm install
      - name: Install Docker Compose 
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Start Services
        run: docker-compose up -d
      - name: Run Unit Tests for Backend
        run: |
          cd backend
          npm test

  # Run Unit Tests for Frontend
  test_frontend:
    runs-on: ubuntu-latest
    needs: build_frontend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd frontend/Green-Nest
          npm install
      - name: Start Services
        run: docker-compose up -d
      - name: Run Unit Tests for Frontend
        run: |
          cd frontend/Green-Nest
          npm test

  # Run Linter and SAST Jobs
  lint_and_sast:
    runs-on: ubuntu-latest
    needs: [test_backend, test_frontend]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd backend
          npm install
          cd ../frontend/Green-Nest
          npm install
      - name: Run Linter for Backend
        run: |
          cd backend
          npm run lint
      - name: Run Linter for Frontend
        run: |
          cd frontend/Green-Nest
          npm run lint

  # Push Docker Images to DockerHub
  push_to_dockerhub:
    runs-on: ubuntu-latest
    needs: [build_backend, build_frontend]
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Backend Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:$GITHUB_SHA
      - name: Push Frontend Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:$GITHUB_SHA
